### ISSUE TITLE
Chrome: opened cards appear behind the info card

### ISSUE THREAD

**Issue by alexanelli** [bizzaro-jhunt/vault-of-cardboard#1]
![screen shot 2018-12-14 at 1 10 12 pm](https://user-images.githubusercontent.com/8454017/50019717-b073d980-ffa1-11e8-9138-59e76146e921.png)

**Comment by jhunt** [comment]
zeee fault is in zee z-index!

**Comment by jhunt** [comment]
I believe this is fixed; @aanelli can you take a look?
