### ISSUE TITLE
Chrome, Safari: List of Cards appear stretched

### ISSUE THREAD

**Issue by davidlohle** [bizzaro-jhunt/vault-of-cardboard#2]
Viewing a list of cards after a search results in the cards being stretched vertically for the whole viewport. This appears to affect all webkit browsers, as Safari and Mobile Safari are also affected.

<img width="1440" alt="screen shot 2018-12-14 at 1 27 32 pm" src="https://user-images.githubusercontent.com/2215601/50020563-50cafd80-ffa4-11e8-91e4-fca3a964b4a4.png">

**Comment by jhunt** [comment]
Apparently, WebKit doesn't honor image aspect ratio the same FF/Quantum does.  Looks like we need to wrap the grid images in a span, and leverage the 63x88 aspect ratio of cards (calculating in terms of `vw` units.)

**Comment by jhunt** [comment]
I believe this is fixed; @Proplex can you take a look?

**Comment by davidlohle** [comment]
Yup, all fixed!
<img width="1440" alt="screen shot 2018-12-14 at 1 42 11 pm" src="https://user-images.githubusercontent.com/2215601/50021155-2b3ef380-ffa6-11e8-8d6e-57ea986fb9d2.png">
